// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6H0By0zfcw6cgGEqeZrBkOLe-xZBZIAw',
    appId: '1:923922157431:web:1e80df46b888c441a55b72',
    messagingSenderId: '923922157431',
    projectId: 'periodliable',
    authDomain: 'periodliable.firebaseapp.com',
    storageBucket: 'periodliable.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLb952Cxdtj_rVHxrl0bh0mlTX_xbLjS0',
    appId: '1:923922157431:android:21f1d4488ef185e9a55b72',
    messagingSenderId: '923922157431',
    projectId: 'periodliable',
    storageBucket: 'periodliable.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwWV_vyy6phQYt4dFt2juATByxTkCx6i4',
    appId: '1:923922157431:ios:74befcf8b3cf24c0a55b72',
    messagingSenderId: '923922157431',
    projectId: 'periodliable',
    storageBucket: 'periodliable.firebasestorage.app',
    iosBundleId: 'com.example.menstrualCycleTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwWV_vyy6phQYt4dFt2juATByxTkCx6i4',
    appId: '1:923922157431:ios:74befcf8b3cf24c0a55b72',
    messagingSenderId: '923922157431',
    projectId: 'periodliable',
    storageBucket: 'periodliable.firebasestorage.app',
    iosBundleId: 'com.example.menstrualCycleTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6H0By0zfcw6cgGEqeZrBkOLe-xZBZIAw',
    appId: '1:923922157431:web:0d4a7b84c768fa1da55b72',
    messagingSenderId: '923922157431',
    projectId: 'periodliable',
    authDomain: 'periodliable.firebaseapp.com',
    storageBucket: 'periodliable.firebasestorage.app',
  );

}